export const actionTypes = {
    START_FETCH_PROJECTS: 'START_FETCH_PROJECTS',
    START_FETCH_PROJECTS_SUCCESS: 'START_FETCH_PROJECTS_SUCCESS',
    START_FETCH_PROJECTS_FAILED: 'START_FETCH_PROJECTS_FAILED',
    CREATE_PROJECT: 'CREATE_PROJECT',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECTS_SUCCESS',
    CREATE_PROJECT_FAILED: 'CREATE_PROJECT_FAILED',

}