export const actionTypes = {
    START_FETCH_PROJECTS: 'START_FETCH_PROJECTS',
    START_FETCH_PROJECTS_SUCCESS: 'START_FETCH_PROJECTS_SUCCESS',
    START_FETCH_PROJECTS_FAILED: 'START_FETCH_PROJECTS_FAILED',

    CREATE_PROJECT: 'CREATE_PROJECT',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECTS_SUCCESS',
    CREATE_PROJECT_FAILED: 'CREATE_PROJECT_FAILED',

    GET_PROJECT: 'GET_PROJECT',
    GET_PROJECT_SUCCESS: 'GET_PROJECTS_SUCCESS',
    GET_PROJECT_FAILED: 'GET_PROJECT_FAILED',

    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILED: 'LOGIN_USER_FAILED',

    LOGOUT_USER: 'LOGOUT_USER',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
    LOGOUT_USER_FAILED: 'LOGOUT_USER_FAILED',

    SIGNUP_USER: 'SIGNUP_USER',
    SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
    SIGNUP_USER_FAILED: 'SIGNUP_USER_FAILED',

    EDIT_PROJECT: 'EDIT_PROJECT',
    EDIT_PROJECT_SUCCESS: 'EDIT_PROJECTS_SUCCESS',
    EDIT_PROJECT_FAILED: 'EDIT_PROJECT_FAILED',

    DELETE_PROJECT: 'DELETE_PROJECT',
    DELETE_PROJECT_SUCCESS: 'DELETE_PROJECTS_SUCCESS',
    DELETE_PROJECT_FAILED: 'DELETE_PROJECT_FAILED',
};